name: Deploy BE to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Publish BE
      run: dotnet publish -c Release -o publish

    - name: Upload publish folder to VPS
      uses: appleboy/scp-action@v0.1.7
      with:
        host: xungxinh.io.vn
        username: root
        password: ${{ secrets.VPS_PASSWORD }}
        source: "publish"
        target: "/var/www/EXE201_DressyProject/BE"

    - name: Restart BE service
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: xungxinh.io.vn
        username: root
        password: ${{ secrets.VPS_PASSWORD }}
        script: |
          systemctl restart be
